name: Deploy to S3.

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: S3 Sync.
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --exclude '.git/*' --exclude '.github/*' --delete
      env:
        AWS_S3_BUCKET: www.nook.zzizily.com
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
