name: Deploy to Develop

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to S3 bucket
    runs-on: ubuntu-latest

    steps:
      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: www.nook.zzizily.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
          SOURCE_DIR: ./
          DEST_DIR: /
